"""job progress stage

Revision ID: 6c6e0759a49e
Revises: eb17c935e9af
Create Date: 2026-08-01 00:27:39.740983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6e0759a49e'
down_revision = 'eb17c935e9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('progress_pct', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('progress_pct')
        batch_op.drop_column('stage')

    # ### end Alembic commands ###
