"""per-plugin timings

Revision ID: fda781d38f87
Revises: 6c6e0759a49e
Create Date: 2026-08-01 20:31:44.056159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda781d38f87'
down_revision = '6c6e0759a49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plugin_seconds', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('plugin_seconds')

    # ### end Alembic commands ###
